// Module included in the following assemblies:
//
// * operators/operator_sdk/golang/osdk-golang-tutorial.adoc
// * operators/operator_sdk/ansible/osdk-ansible-tutorial.adoc
// * operators/operator_sdk/helm/osdk-helm-tutorial.adoc

:osdk_ver: v1.3.0
ifeval::["{context}" == "osdk-golang-tutorial"]
:golang:
:type: Go
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:ansible:
:type: Ansible
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:helm:
:type: Helm
endif::[]

[id="osdk-prepare-supported-images_{context}"]
= Preparing your Operator to use supported images

Before running your {type}-based Operator on {product-title}, update your project to use supported images.

.Procedure

ifdef::golang[]
. Update the following lines in the project root-level Dockerfile to use supported images.

.. Change the default builder image reference from:
+
[source,terminal]
----
golang:1.15
----
+
to:
+
[source,terminal]
----
registry.redhat.io/openshift4/builder:rhel-8-golang-1.15-openshift-4.7
----

.. Change the default runner image reference from:
+
[source,terminal]
----
gcr.io/distroless/static:nonroot
----
+
to:
+
[source,terminal]
----
registry.access.redhat.com/ubi8/ubi-minimal:latest
----

.. Remove the `USER: nonroot:nonroot` directive, as it is not required by the supported image.

. In the `config/default/manager_auth_proxy_patch.yaml` file, change the `image` value from:
+
[source,terminal]
----
gcr.io/kubebuilder/kube-rbac-proxy:<tag>
----
+
to use the supported image:
+
[source,terminal,subs="attributes+"]
----
registry.redhat.io/openshift4/ose-kube-rbac-proxy:v{product-version}
----
endif::[]

ifdef::ansible[]
* Update the project root-level Dockerfile to use supported images. Change the default builder image reference from:
+
[source,terminal,subs="attributes+"]
----
FROM quay.io/operator-framework/ansible-operator:{osdk_ver}
----
+
to:
+
[source,terminal,subs="attributes+"]
----
FROM registry.redhat.io/openshift4/ose-ansible-operator:v{product-version}
----
endif::[]

ifdef::helm[]
* Update the project root-level Dockerfile to use supported images. Change the default builder image reference from:
+
[source,terminal,subs="attributes+"]
----
FROM quay.io/operator-framework/helm-operator:{osdk_ver}
----
+
to:
+
[source,terminal,subs="attributes+"]
----
FROM registry.redhat.io/openshift4/ose-helm-operator:v{product-version}
----
endif::[]

:!osdk_ver:
ifeval::["{context}" == "osdk-golang-tutorial"]
:!golang:
:!type:
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:!ansible:
:!type:
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:!helm:
:!type:
endif::[]
