// Module included in the following assemblies:
//
// * operators/operator_sdk/golang/osdk-golang-tutorial.adoc
// * operators/operator_sdk/ansible/osdk-ansible-tutorial.adoc
// * operators/operator_sdk/helm/osdk-helm-tutorial.adoc

ifeval::["{context}" == "osdk-golang-tutorial"]
:golang:
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:ansible:
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:helm:
endif::[]

[id="osdk-bundle-deploy-olm_{context}"]
= Bundling and deploying with OLM

Operator Lifecycle Manager (OLM) helps you to install, update, and generally manage the lifecycle of Operators and their associated services on a Kubernetes cluster. OLM is installed by default on {product-title} and runs as a Kubernetes extension so that you can use the web console and the OpenShift CLI (`oc`) for all Operator lifecycle management functions without any additional tools.

This example walks through getting an Operator ready for OLM that uses the Bundle Format, the default packaging format for Operator SDK and OLM.

ifdef::golang[]
.Prerequisites

* Prepared your Go-based Operator to run on {product-title} by updating the project to use supported images
endif::[]

.Prerequisites

- Operator SDK CLI installed on a development workstation
- OpenShift CLI (`oc`) v{product-version}+ installed
- Operator Lifecycle Manager (OLM) installed on a Kubernetes-based cluster (v1.16.0 or later if you use `apiextensions.k8s.io/v1` CRDs, for example {product-title} {product-version})
- Logged into the cluster with `oc` using an account with `cluster-admin` permissions
- Operator built by using the Operator SDK
- Prepared your Operator to run on {product-title} by updating the project to use supported images

.Procedure

. Check the status of OLM on your cluster by using the following Operator SDK command:
+
[source,terminal]
----
$ operator-sdk olm status \
    --olm-namespace=openshift-operator-lifecycle-manager
----

. Create your Operator bundle manifest by running the `make bundle` command, which invokes several commands, including the Operator SDK `generate bundle` and `bundle validate` subcommands:
+
[source,terminal]
----
$ make bundle
----
+
Bundle manifests for an Operator describe how to display, create, and manage an application. The `make bundle` command creates the following files and directories in your Operator project:
+
--
* A bundle manifests directory `bundle/manifests` containing a `ClusterServiceVersion` (CSV) object
* A bundle metadata directory `bundle/metadata`
* All CRDs in `config/crd`
* A Dockerfile `bundle.Dockerfile`
--
+
These files are then automatically validated by using `operator-sdk bundle validate` to ensure the on-disk bundle representation is correct.

. Build and push your bundle image by running the following commands. OLM consumes Operator bundles using an index image, which reference one or more bundle images.

.. Build the bundle image. Set `BUNDLE_IMAGE` with the details for the registry, user namespace, and image tag where you intend to push the image:
+
[source,terminal]
----
$ make bundle-build BUNDLE_IMG=<registry>/<user>/<image_name>:<tag>
----

.. Push the bundle image:
+
[source,terminal]
----
$ docker push <registry>/<user>/<image_name>:<tag>
----

. Run the Operator on your cluster by using the OLM integration in Operator SDK:
+
[source,terminal]
----
$ operator-sdk run bundle <registry>/<user>/<image_name>:<tag>
----
+
This command performs the following actions:
+
--
* Create an index image with your bundle image injected.
* Create a catalog source that points to your new index image, which enables OperatorHub to discover your Operator.
* Deploy your Operator to your cluster by creating an Operator group, subscription, install plan, and all other required objects, including RBAC.
--

ifeval::["{context}" == "osdk-golang-tutorial"]
:!golang:
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:!ansible:
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:!helm:
endif::[]
